apiVersion: 1
contactPoints:
    - orgId: 1
      name: github-alert
      receivers:
        - uid: github_repo_webhook
          type: webhook
          settings:
            httpMethod: POST
            url: http://alert-proxy:5000/webhook
            message: |+
                {{ define "default.message" }}{{ if gt (len .Alerts.Firing) 0 }}**Firing**
              
                {{ template "__text_alert_list" .Alerts.Firing }}{{ if gt (len .Alerts.Resolved) 0 }}

                {{ end }}{{ end }}{{ if gt (len .Alerts.Resolved) 0 }}**Resolved**
                {{ template "__text_alert_list" .Alerts.Resolved }}{{ end }}{{ end }}

            title: '{{ template "default.title" . }}'
          disableResolveMessage: true
