{
 "title": "Airflow overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(airflow_scheduler_tasks_executable,job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(airflow_scheduler_tasks_executable{job=~\"$job\"}, instance)"
   },
   {
    "name": "dag_id",
    "label": "DAG",
    "query": "label_values(airflow_task_start_total{}, dag_id)"
   },
   {
    "name": "task_id",
    "label": "Task",
    "query": "label_values(airflow_task_start_total{job=~\"$job\", instance=~\"$instance\", dag_id=~\"$dag_id\"}, task_id)"
   },
   {
    "name": "state",
    "label": "Task state",
    "query": "label_values(airflow_task_finish_total{job=~\"$job\", instance=~\"$instance\", dag_id=~\"$dag_id\", task_id=~\"$task_id\"}, state)"
   },
   {
    "name": "pool_name",
    "label": "Pool",
    "query": "label_values(airflow_pool_open_slots{job=~\"$job\", instance=~\"$instance\"}, pool_name)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "DAG file parsing errors",
   "type": "timeseries",
   "description": "The number of errors from trying to parse DAG files in an Apache Airflow system.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "airflow_dag_processing_import_errors{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Task failures",
   "type": "timeseries",
   "description": "The overall task instances failures for an Apache Airflow system.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(airflow_ti_failures{job=~\"$job\",  instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DAG failed duration",
   "type": "timeseries",
   "description": "The average time taken for recent failed DAG runs",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(airflow_dagrun_duration_failed_sum{job=~\"$job\", instance=~\"$instance\", dag_id=~\"$dag_id\"}[$__interval:])/clamp_min(increase(airflow_dagrun_duration_failed_count{job=~\"$job\", instance=~\"$instance\", dag_id=~\"$dag_id\"}[$__interval:]),1)",
     "legendFormat": "{{dag_id}}"
    }
   ]
  },
  {
   "title": "DAG success duration",
   "type": "timeseries",
   "description": "The average time taken for recent successful DAG runs",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(airflow_dagrun_duration_success_sum{job=~\"$job\", instance=~\"$instance\", dag_id=~\"$dag_id\"}[$__interval:])/clamp_min(increase(airflow_dagrun_duration_success_count{job=~\"$job\", instance=~\"$instance\", dag_id=~\"$dag_id\"}[$__interval:]),1)",
     "legendFormat": "{{dag_id}}"
    }
   ]
  },
  {
   "title": "Airflow Task Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{job=~\".+\", cluster=~\".*\", instance=~\".+\", dag_id=~\"$dag_id\", task_id=~\"$task_id\", filename=~\".*/airflow/logs/dag_id.*\"}"
    }
   ]
  }
 ]
}